export default {
    gender: {
        'Male': '男',
        'Female': '女'
    },
    days: {
        'Monday': '星期一',
        'Tuesday': '星期二',
        'Wednesday': '星期三',
        'Thursday': '星期四',
        'Friday': '星期五',
        'Saturday': '星期六',
        'Sunday': '星期日'
    },
    locations: {
        'Central and Western': '中西區',
        'Eastern': '東區',
        'Islands': '離島區',
        'Kowloon': '九龍',
        'Kwai Tsing': '葵青',
        'Kwun Tong': '觀塘',
        'North': '北區',
        'Other': '其他',
        'Sai Kung': '西貢',
        'Sha Tin': '沙田',
        'Sham Shui Po': '深水埗',
        'Southern': '南區',
        'Tai Po': '大埔',
        'Tsuen Wan': '荃灣',
        'Tuen Mun': '屯門',
        'Wan Chai': '灣仔',
        'Wong Tai Sin': '黃大仙',
        'Yau Tsim Mong': '油尖旺',
        'Yuen Long': '元朗'
    },
    countries: {
        'Hong Kong': '香港', 
        'China': '中國', 
        'Singapore': '新加坡',
        'Malaysia': '馬來西亞', 
        'India': '印度'
    },
    religions: {
        'Buddhist': "佛教",
        'Catholic': "天主教",
        'Christian': "基督教",
        'Hindu': "印度教",
        'Muslim': "回教",
        'Other': "其他宗教",
        'Taoist': "道教"
    },
    languages: {
        'Cantonese': "廣東話",
        'English': "英語",
        'French': "法語",
        'German': "德語",
        'Italian': "意大利語",
        'Japanese': "日語",
        'Korean': "韓語",
        'Putonghua': "普通話",
        'Spanish': "西班牙語",
        'Tagalog': "菲律賓語"
    },
    serviceType: {
        'Live-in': '留宿',
        'Live-out': '不留宿'
    },
    careTypes: {
        "Eldercare": "長者護理",
        "Expert": "專家",
        "Home Nurse": "家庭護士",
        "Licensed Nurse": "持牌護士",
        "Nursing Students": "護理系學生",
        "Special Needs": "特殊需要",
        "Specialist": "專科護理員",
        "Sports Buddies": "運動夥伴",
        "TLC": "關愛護理",
        "Volunteer": "志願者",
        "Weekend": "週末"
    },
    professional: {
        'Addiction Counselor': "沉溺輔導員",
        'Beautician': "美容師",
        'Chinese Medicine Expert': "中藥師",
        'Chiropractor': "脊醫",
        'Eldercare': "長者護理員",
        'Hair Stylist': "髮型師",
        'Licensed Nurse': "持牌護士",
        'Massage Therapist': "按摩師",
        'Midwife': "助產士",
        'Occupational Therapist': "職業治療師",
        'Personal Trainer': "私人健身教練",
        'Physiotherapist': "物理治療師",
        'Reflexologist': "脚底按摩師",
        'Special Needs Therapist': "特殊需要護理員",
        'Speech Therapist': "語言治療師",
        'Spiritual/Body/Mind Expert': "精神/身體/心靈專家",
        'Sports Therapist': "運動治療師",
        'Yoga Instructor': "瑜伽導師"
    },
    personal: {
        'Bathing': "洗澡",
        'Companionship': "陪伴",
        'Exercise': "運動",
        'Groceries and Shopping': "購物",
        'Grooming': "美容",
        'Housekeeping': "家務",
        'Managing Medications': "用藥管理",
        'Meal Prep': "膳食準備",
        'Toileting': "如廁",
        'Transferring and Mobility': "搬移及走動",
        'Transportation': "交通",
        'Travel Companion': "旅遊夥伴"
    },
    medical: {
        "ALS": "肌萎縮性脊髓側索硬化症",
        "Allergy": "過敏",
        "Alzheimer's Disease": "阿茲海默症",
        "Anemia": "貧血",
        "Arthritis": "關節炎",
        "Asthma": "哮喘",
        "Autism/ADHD": "自閉症/過動症",
        "Blindness": "失明",
        "Blood Disorders": "血液系统疾病",
        "Breast Disease": "乳房疾病",
        "COPD": "慢性阻塞性肺病",
        "Cancer": "癌症",
        "Cardiovascular Disorders": "心血管疾病",
        "Dementia": "癡呆症",
        "Depression": "抑鬱",
        "Diabetes": "糖尿病",
        "Foot Problem": "足部問題",
        "Gastronomical Disorders": "進食失調",
        "HIV/AIDS": "愛滋病護理",
        "Hearing Disorders": "聽力障礙",
        "Home Healthcare": "家庭健康護理",
        "Hospice Care": "善終照料",
        "Hypertension": "高血壓",
        "Kidney Disease": "腎臟疾病",
        "Multiple Sclerosis": "多發性硬化症",
        "Neurological Disorders": "神經系統失調",
        "Orthopedic Care": "矯形外科護理",
        "Palliative Care": "寧養療護",
        "Parkinson's Disease": "柏金遜症",
        "Post Surgery Recovery": "術後復元",
        "Renal and Urological Disorders": "腎臟和泌尿系統疾病",
        "Respiratory Disorders": "呼吸系統疾病",
        "Skin Disorders": "皮膚疾病",
        "Stroke": "中風",
        "Tracheotomy/Ventilation": "氣管造口",
        "Vision and Eye Disorders": "視覺受捐及眼科疾病"
    }
}